version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
        - NEXTAUTH_URL=${NEXTAUTH_URL}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    networks:
      - default
  db:
    image: postgres:13-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    networks:
      - default
  mailer:
    image: mailhog/mailhog
    networks:
      - default
    ports:
      - 8025:8025
  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
      args:
        - DATABASE_URL=postgres://postgres:password@db:5432/app
    env_file:
      - .env.docker
    depends_on:
      - db
    profiles:
      - migrate
    networks:
      - default

volumes:
  postgres-data:


networks:
  default:
