version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/app
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - node-modules:/app/node_modules
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
  db-test:
    image: postgres:13-alpine
    ports:
      - "54321:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
volumes:
  postgres-data:
  node-modules:
