FROM node:18.17.0

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

WORKDIR /app

COPY package.json /app
COPY package-lock.json /app
COPY prisma /app/prisma


RUN npm ci

CMD npx prisma migrate deploy